### ISSUE TITLE
Implement variadic params for fn's

### ISSUE THREAD

**Issue by titpetric** [kortschak/utter#11]
It would be nice for Dump and other functions to take a `...interface{}`, to support dumping several variables at once. Dumping with len() == 0 would result in a panic or a nil. Keeps backward compatibility.

**Comment by kortschak** [comment]
I actually removed variadic arguments (they exist in spew), because I don't think they fit with the use cases for utter. You can get something that looks like variadic print arguments by passing a slice literal of the appropriate type to `Dump`, e.g. `utter.Dump([]interface{}{a, b, c})`.

If you can give me a compelling set of real world use cases that need variadic arguments, I'll reconsider.

**Comment by kortschak** [comment]
This has been silent for almost a year.
