### ISSUE TITLE
feature request: no string escaping

### ISSUE THREAD

**Issue by mschneider82** [kortschak/utter#29]
Feature Request:

Config Option to change string output to use `` instead of "" with escaping:

current output:
```
Test: string("/\\<.{1,50}\\@.{1,50}\\@.{1,50}\\>/i")
```
could be:
```
Test string(`/\<.{1,50}\@.{1,50}\@.{1,50}\>/i`)
```

**Comment by kortschak** [comment]
I was just thinking about this yesterday. It's more complex than it seems. There are two major issues, the first is a matter of aesthetics and safety; printing with backtick-quoted strings can cause whitespace characters to be emitted such as new line, tab and so on. Having these characters in the output rendered as control characters rather than the escape sequence can make the output harder to read and more likely to be silently damaged by an editor. The second issue is that backtick-quoted strings cannot contain backticks.

So this means that there are prechecks that need to be done prior to printing a string literal using backticks, beyond checking whether it is necessary. Deciding how far to push is a non-trivial UI design problem. It's certainly something that's worth looking at though. Do you have ideas about approaches? I would prefer a single value configuration, which means that it becomes either a set of bit flags or a `func(string) bool` (the latter is less appealing).

**Comment by kortschak** [comment]
@mschneider82 Please take a look at the sketch at #30.

**Comment by mschneider82** [comment]
Thanks, i think the backticks or Others problematic Chats could be added by using `+"'"+`
Ist not pretty but a rare Case

**Comment by kortschak** [comment]
Yes, that's the approach that I've take in #30. Please take a look and see if the API looks reasonable.
